name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: ['11', '11-ea', 'openjdk11', 'openjdk-ea']
        include:
          - java-version: '11'
            distribution: 'adopt'
          - java-version: '11-ea'
            distribution: 'adopt'
          - java-version: 'openjdk11'
            distribution: 'adopt'
          - java-version: 'openjdk-ea'
            distribution: 'adopt'
        exclude:
          - java-version: '11-ea'
          - java-version: 'openjdk-ea'

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.distribution }}
        cache: maven

    - name: Install dependencies
      run: mvn -q install -Dgpg.skip

    - name: Build and test
      run: mvn -q clean compile test
