name: Java CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: ['11', '11-ea', 'openjdk11', 'openjdk-ea']
        exclude:
          - java-version: '11-ea'
          - java-version: 'openjdk-ea'

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'
        cache: maven

    - name: Install dependencies
      run: mvn -q install -Dgpg.skip

    - name: Build and test
      run: mvn -q clean compile test
