name: gha-result

on:
  workflow_dispatch:
  push:
    branches:
      - branch-1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.0

      - name: Setup Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: zulu
          java-version: '11' # Java version updated to 11

      - name: Set up cache
        uses: actions/cache@v3.3.1
        with:
          path: "${{ github.workspace }}/.m2"
          key: "${{ runner.os }}-path"

      - run: mvn -q install -Dgpg.skip

      - run: mvn -q clean compile test

      - run: bash <(curl -s https://codecov.io/bash)
        if: "${{ success() }}"
