name: placeholder_Name

on:
  pull_request:
    branches: 
      - branch-name
  push:
    branches:
      - branch-2

jobs:
  build:
    strategy:
      matrix:
        java: [ '19-ea', '18-ea' ]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin' 
   
    - name: Build with Maven
      run: mvn -q clean compile test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
